#!/usr/bin/env python3

# roi_report.py - One-page ROI summary for stakeholders

import sqlite3
from datetime import datetime

def generate_roi_report():
		"""Generate executive ROI summary"""
	
		conn = sqlite3.connect('sales_angel.db')
	
		enriched = conn.execute("SELECT COUNT(*) FROM contacts WHERE enriched = 1").fetchone()[0]
		with_content = conn.execute("SELECT COUNT(*) FROM contacts WHERE email_1_subject IS NOT NULL").fetchone()[0]
	
		# Read activity from CSV
		try:
				import csv
				with open('daily_tracker.csv', 'r') as f:
						reader = csv.DictReader(f)
						activities = list(reader)
					
				emails = len([a for a in activities if a.get('Channel') == 'Email'])
				responses = len([a for a in activities if 'response' in a.get('Channel', '').lower()])
				meetings = len([a for a in activities if 'meeting' in a.get('Status', '').lower()])
		except:
				emails, responses, meetings = 0, 0, 0
			
		# Costs
		total_cost = (enriched * 0.15) + (with_content * 0.05)
	
		# Value
		pipeline_low = meetings * 45000 * 0.10
		pipeline_high = meetings * 450000 * 0.10
	
		# Create report
		report = f"""
╔══════════════════════════════════════════════════════════════════════╗
║                    SALES ANGEL ROI REPORT                            ║
║                    {datetime.now().strftime('%B %d, %Y')}                                        ║
╚══════════════════════════════════════════════════════════════════════╝

📊 ACTIVITY SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

	Contacts Enriched:        {enriched:>5}
	Content Generated:        {with_content:>5} contacts ({with_content * 6:>5} pieces)
	
	Outreach Executed:
		• Emails Sent:          {emails:>5}
		• Responses Received:   {responses:>5} ({(responses/emails*100) if emails > 0 else 0:>4.1f}%)
		• Meetings Booked:      {meetings:>5}

💰 FINANCIAL IMPACT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

	Investment:               ${total_cost:>10,.2f}
	
	Pipeline Created:
		• Conservative:         ${pipeline_low:>10,.0f}
		• Optimistic:           ${pipeline_high:>10,.0f}
	
	Return on Investment:
		• Low Scenario:         {((pipeline_low-total_cost)/total_cost*100) if total_cost > 0 else 0:>10,.0f}%
		• High Scenario:        {((pipeline_high-total_cost)/total_cost*100) if total_cost > 0 else 0:>10,.0f}%
	
	Cost Efficiency:
		• Per Enrichment:       ${total_cost/enriched if enriched > 0 else 0:>10,.2f}
		• Per Email:            ${total_cost/emails if emails > 0 else 0:>10,.2f}
		• Per Response:         ${total_cost/responses if responses > 0 else 0:>10,.2f}
		• Per Meeting:          ${total_cost/meetings if meetings > 0 else 0:>10,.2f}

🎯 PERFORMANCE BENCHMARKS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

	Email Response Rate:      {(responses/emails*100) if emails > 0 else 0:>6.1f}%  (Target: 25%)
	Meeting Conversion:       {(meetings/responses*100) if responses > 0 else 0:>6.1f}%  (Target: 30%)
	Cost per Meeting:         ${total_cost/meetings if meetings > 0 else 0:>8,.2f}  (Industry: $200-500)

📈 NEXT STEPS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

	1. Scale enrichment to 50+ contacts
	2. Maintain 3+ emails sent per day
	3. Follow up on all responses within 24 hours
	4. Track closed deals to calculate actual ROI

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Sales Angel v3.0 | For questions: [your email]
"""

		conn.close()
		return report
		
if __name__ == "__main__":
		print(generate_roi_report())
	